[package]
name = "gpt-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
chatgpt_rs = "1.2.3"
clap = { version = "4.5.23", features = ["derive"] }
thiserror = "2.0.9"
tokio = { version = "1.42.0", features = ["full"] }
