[package]
name = "gpt-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
chatgpt_rs = "1.2.3"
clap = { version = "4.5.23", features = ["derive"] }
env_logger = "0.11.6"
log = "0.4.22"
thiserror = "2.0.9"
tokio = { version = "1.42.0", features = ["full"] }
url = "2.5.4"
